server:
  port: 8080
  servlet:
    context-path: /producer
    
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      bindings:
        producerOutput:                   # you can write here what you want! 
          destination: topicMessage
          content-type: application/json
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost
